server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: validate # ?? ????? create-drop, ?? ????? validate ??
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}